### ISSUE TITLE
how control select type width in popup

### ISSUE THREAD

**Issue by matebe12** [bosskmk/pluto_grid#137]
hi  i have a question

![image](https://user-images.githubusercontent.com/42566975/106435382-48054200-641f-11eb-8669-63a41afaf96a.png)
how remove this popup space ??

**Comment by bosskmk** [comment]
PlutoGrid uses flutter's dialog as a way to display popups, which has constraints (min-width: 280) so it doesn't shrink below that.

https://github.com/flutter/flutter/blob/9b2d32b605/packages/flutter/lib/src/material/dialog.dart#L147

To get rid of the right margin, I think there are two ways.

1. Make a CustomDialog so that you can change the Constraints of the dialog.
2. Fill the right margin by changing the width of the column from 200 to 280.

Both of these require updating.

I think it is better to increase the default width to 280, which is the second method.

I might add it in the next update.

**Comment by BangPei** [comment]
hi, i have plutoColumn with type select, i fill list from list Of Object.

PlutoColumn(
            title: "Uom",
            field: 'uom',
            type: PlutoColumnType.select(
                _listUom.map((e) => e?.name ?? "--").toList()),
          ),

can i get an object value when i select onChanged?
or just string can be catched?

**Comment by ecoant** [comment]
Any update on this? The popup seems to be totally un-configurable. The default style/size looks incorrect for desktop apps, and there doesn't seem to be any way to modify the sizing. The "auto-fit" menu option present in the popup does help, but I am unable to set this menu option to enabled by default. It appears the popup ignores the user-defined `columnMenuDelegate` of `PlutoGrid`.
