### ISSUE TITLE
Save and restore states of PlutoGrid.

### ISSUE THREAD

**Issue by Haetsal-Lee** [bosskmk/pluto_grid#138]
I want to save and restore states of PlutoGrid.

The state I mean which include 1)order of reordered columns (moved) 2) applied filters and so on.

And is there a callback or event after moving columns? So that I can save states after the moving columns?
I am trying to read codes in detail but little confused now. How "Event" and "States" are different?

Thanks

**Comment by bosskmk** [comment]
Logic that needs processing like debounce and throttle is 'evnet', otherwise most logic is 'state'.

I've thought about saving a state history to revert to state or keystrokes, etc., but I'm not having time to implement it.

**Comment by exomaniac** [comment]
if i can find a little time i can make an example. we are doing exactly this, but it is not so elegant.
We save some state (columnindex, sort, applied filters , etc ) to json and store them to later load them again.

**Comment by bosskmk** [comment]
@exomaniac 
That's a good approach.

**Comment by FloRul** [comment]
Is this still relevant ? because recently I had a similar solution that was working to store the columns order and restore it on the onLoaded event. Right now on the 5.0.6 version I have this bug :
 ════════ Exception caught by widgets library ═══════════════════════════════════
The following _CastError was thrown while rebuilding dirty elements:
Null check operator used on a null value

The relevant error-causing widget was
PlutoGrid
lib\main.dart:65
When the exception was thrown, this was the stack
#0      ContainerRenderObjectMixin._debugUltimatePreviousSiblingOf
package:flutter/…/rendering/object.dart:3627
#1      ContainerRenderObjectMixin._insertIntoChildList
package:flutter/…/rendering/object.dart:3709
#2      ContainerRenderObjectMixin.move
package:flutter/…/rendering/object.dart:3822
#3      PlutoVisibilityLayoutRenderObjectElement.moveRenderObjectChild
package:pluto_grid/…/miscellaneous/pluto_visibility_layout.dart:344
#4      RenderObjectElement._updateSlot
package:flutter/…/widgets/framework.dart:6071
#5      Element.updateSlotForChild.visit
package:flutter/…/widgets/framework.dart:3701
#6      ComponentElement.visitChildren
package:flutter/…/widgets/framework.dart:4931
#7      Element.updateSlotForChild.visit
package:flutter/…/widgets/framework.dart:3703
#8      ComponentElement.visitChildren
package:flutter/…/widgets/framework.dart:4931
#9      Element.updateSlotForChild.visit
package:flutter/…/widgets/framework.dart:3703
#10     Element.updateSlotForChild
package:flutter/…/widgets/framework.dart:3706
#11     Element.updateChild
package:flutter/…/widgets/framework.dart:3549
#12     RenderObjectElement.updateChildren
package:flutter/…/widgets/framework.dart:5964
#13     PlutoVisibilityLayoutRenderObjectElement.performRebuild
package:pluto_grid/…/miscellaneous/pluto_visibility_layout.dart:233
#14     Element.rebuild
package:flutter/…/widgets/framework.dart:4604
#15     BuildOwner.buildScope
package:flutter/…/widgets/framework.dart:2667
#16     WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:882
#17     RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:378
#18     SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1175
#19     SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1104
#20     SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:1015
#21     _invoke (dart:ui/hooks.dart:148:13)
#22     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#23     _drawFrame (dart:ui/hooks.dart:115:31)
The element being rebuilt at the time was index 0 of 1: PlutoVisibilityLayout
    renderObject: RenderCustomMultiChildLayoutBox#ed68f relayoutBoundary=up16 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE
════════════════════════════════════════════════════════════════════════════════
Here is the link to a minimal project to reproduce (desktop build). The exception is thrown when I try to scroll horizontally.
https://bitbucket.org/FloRul/pluto_test/src/master/

**Comment by rickmeulendijks** [comment]
> if i can find a little time i can make an example. we are doing exactly this, but it is not so elegant. We save some state (columnindex, sort, applied filters , etc ) to json and store them to later load them again.
> 
> here some code we use:
> 
> ```dart
>   ///set the correct column order
>   void setColumnOrder() {
>     if (configuration == null) {
>       stateManager?.refColumns?.originalList?.sort();
>     } else {
>       var ix = Map.fromEntries(
>           configuration.columns.map((e) => MapEntry(e.field, e.index ?? 0)));
>       stateManager.refColumns.sort((a, b) {
>         if (a == null || b == null) {
>           return 0;
>         }
>         if (ix.containsKey(a.field) && ix.containsKey(b.field)) {
>           return ix[a.field].compareTo(ix[b.field]);
>         }
>         return 0;
>       });
>     }
> 
>     stateManager.refColumns.update();
>   }
> 
>   ///set column properties
>   void setColumnProperties() {
>     for (var col in configuration.columns) {
>       var ocol = stateManager?.refColumns?.originalList?.singleWhere(
>           (element) => element.title == col.title,
>           orElse: (() => null));
>       if (ocol != null) {
>         stateManager?.hideColumn(ocol.key, col.hide);
>         ocol.width = col.width;
>         ocol.minWidth = col.minWidth;
>       }
>     }
>   }
> 
>   ///set the filters of the current configuration
>   void setFilter() {
>     var filterRows = configuration?.filters
>         ?.map((e) => PlutoRow(cells: {
>               'column': PlutoCell(value: e.column),
>               'type': PlutoCell(value: e.getTypeFromString()),
>               'value': PlutoCell(value: e.value)
>             }))
>         ?.toList();
>     stateManager?.setFilterWithFilterRows(filterRows ?? []);
>   }
> 
>   ///set the current cell position
>   void setCurrentCellPosition() {
>     if (stateManager.currentCell == null && stateManager.refRows.isNotEmpty) {
>       var cell = configuration.position == null
>           ? null
>           : stateManager.refRows
>               .firstWhere(
>                   (element) =>
>                       element.sortIdx == configuration.position.rowIndex,
>                   orElse: () => null)
>               ?.cells
>               ?.entries
>               ?.firstWhere(
>                   (element) => element.key == configuration.position.field,
>                   orElse: () => null)
>               ?.value;
>       if (cell == null) {
>         cell = stateManager.refRows.first.cells.values.first;
>       }
>       stateManager.setCurrentCell(
>         cell,
>         configuration.position.rowIndex,
>         notify: true,
>       );
>     }
>   }
> ```

@exomaniac do you have perhaps an example of how you save your configuration in the JSON you mention? I'm looking for a similar solution to store filter and column settings. When do you trigger the "save to JSON" when someone is filtering or ordering the columns?
