### ISSUE TITLE
Strange behavior of keyboard on Android

### ISSUE THREAD

**Issue by lvyandev** [bosskmk/pluto_grid#341]
https://user-images.githubusercontent.com/18045999/146857253-1ebe83cc-de71-4fbc-b080-62223bdaffdb.mp4

Tap Done or Submit button doesn't hide keyboard.

Also, during input onChange event is not triggered. 
Only if press the Done button on keyboard or change current cell position to another can change the cell value.
If I save the table data without these actions then the input new value would be ignored

https://user-images.githubusercontent.com/18045999/146862150-7f1ba004-6374-4e08-ad92-7ebab4ff4c8f.mp4

**Comment by bosskmk** [comment]
I'll modify it so that tapping Done has the same action as the Enter key.

And the onChanged callback is only called when the actual value has changed.

TextField 's onChanged callback currently has no external API.
If necessary, you can access the TextField's TextEditingController as stateManager.textEditingController .
Of course, this is only possible after the widget is mounted.

I will consider adding a callback for inputting text in a future version.

Thanks for the bug report.
