### ISSUE TITLE
TextField as cell renderer cannot delete input content

### ISSUE THREAD

**Issue by lvyandev** [bosskmk/pluto_grid#364]
It works well on emulator, however when I test on real device, there is the problem.

Tested on Samsung SM 9550 and redmi K40.
```dart
PlutoColumn(
        title: 'column3',
        field: 'column3',
        type: PlutoColumnType.text(),
        renderer: (context) {
          return TextField();
        },
      ),
```

https://user-images.githubusercontent.com/18045999/149501618-6befca8f-2f8e-4b9d-a26b-5ca13ba07ca2.mp4

**Comment by bosskmk** [comment]
Doesn't that issue happen with pure flutter and not with PlutoGrid ?

**Comment by lvyandev** [comment]
Yes, it only happens when I use TextField as renderer. Also, if content come up with keyboard recommendations, then content can be deleted.

**Comment by bosskmk** [comment]
Unfortunately I develop on Windows and my actual mobile device is an iPhone.
I can't test it on a real device.

In the current state, there is no problem if you use the built-in text widget instead of the renderer ?

Then, if you tell me why you use renderer for the built-in text widget, adding that function to the built-in widget is considered the first solution.
(If your function is universal, I'll make sure to add it in the next version.)

Or please suggest another solution.

**Comment by lvyandev** [comment]
build-in text widget has no problem on input, but I do find it has some focus problem on very rare situations which I cannot reproduce now, I would check again if I use it correctly. Thank you!  😁

**Comment by lvyandev** [comment]
Another reason I'd like to replace it is that current number type has default value `0`,  cannot accept empty or null value on this type.

**Comment by lvyandev** [comment]
My job is migrating website business to mobile device, so I found issues mainly on mobile.😆😆

**Comment by bosskmk** [comment]
If you give me a feature or opinion about mobile, I will try to reflect it.
I am a web backend developer mainly using nodejs. 😆

**Comment by lvyandev** [comment]
If next version can accept cell null value, it would be nice.
