### ISSUE TITLE
[Bug] Bad GPU performance in PlutoVisibilityLayout 

### ISSUE THREAD

**Issue by MajedDH** [bosskmk/pluto_grid#508]
I profiled the Grid using large number of cells on a wide screen (21:9) the raster part of the profile is taking too long (that's a desktop profile!, it's supposed to be blazing fast) 

Here is an image of a couple of frames: as you can see it is taking 25ms on average: 

![image](https://user-images.githubusercontent.com/3973115/179396689-fb770f71-cdda-4ced-bc3b-9a8b29fbbbd2.png)

but removing the `RepaintBoundary` from `PlutoVisibilityLayoutChild` makes it much better: ~10ms
![image](https://user-images.githubusercontent.com/3973115/179396968-2e0520a6-7afa-4932-a74e-509d78da41d3.png)

Using repaint boundary makes layers or masks or something that when used a lot which makes the operation expensive on the raster thread:

![image](https://user-images.githubusercontent.com/3973115/179397513-a7fd3179-e539-4b35-b697-66e71dfdf03b.png)

after removing the repaint boundary:
![image](https://user-images.githubusercontent.com/3973115/179397596-7ad8e6eb-607c-4269-8508-399c69b80075.png)

I've tried to set the boundary at row level but it was worse than removing it at all.

Maybe it should be mentioned in the documentation that when implementing custom cells in the grid if the custom cell has a heavy price when painting it should be used with repaint boundary.

**Flutter version**
 
Flutter version is 3.0.0
 

**PlutoGrid version**
 
on the Develop branch ef8c7274
 

**OS**
 
Windows 11

**Comment by bosskmk** [comment]
@MajedDH 
Thanks for providing test information for profiling.

So, as per your comments, I'll remove the `RepaintBoundary` and add the content for the `RepaintBoundary` to the document in the custom cell.

And overall I'll keep reviewing and tweaking things about performance when rendering large amounts of cells.

**Comment by bosskmk** [comment]
https://user-images.githubusercontent.com/5284141/179402073-692fb886-5489-4d31-b13d-13934640b242.mp4

The video tested when RepaintBoundary was applied and when not.

It is RepaintBoundary from the beginning to about 22 seconds.

22 seconds to the end is not a RepaintBoundary.

Raster Thread seems to perform slightly better when not RepaintBoundary .

RepaintBoundary: about 16ms
Not RepaintBoundary: about 12ms

The reason I added RepaintBoundary in the first place is to prevent unnecessary repaint because all cells become Repaint whenever horizontally scrolled.

From your tests and my tests, it seems that repainting brings better results for Raster Thread performance.

Conclusion: Remove RepaintBoundary as your comment, and add to docs to consider using RepaintBoundary optionally in case user set custom cell.

**Comment by bosskmk** [comment]
Updated to PlutoGrid version 5.0.4.

**Comment by MajedDH** [comment]
Should I do the change ? or you'll do it?

**Comment by bosskmk** [comment]
@MajedDH 
I worked and distributed 5.0.4.

That commit.
https://github.com/bosskmk/pluto_grid/pull/509/commits/6ee1ce1897f8c8a15c6cb99422a1ab5a19aa0692
