### ISSUE TITLE
[Feature] Sorting progress indicator

### ISSUE THREAD

**Issue by MRKDaGods** [bosskmk/pluto_grid#649]
Sorting of large data freezes the app, maybe add a popup displaying 'Sorting...' or something?

**Comment by bosskmk** [comment]
I've been thinking about this.
Currently, the way I sort a large list without UI freezing is
Each step of merge sort is properly divided and processed asynchronously.
If anyone knows a better way, I'd appreciate it if you could leave it here.

**Comment by thegioiso** [comment]
I think we should left backend server doing this sort. Because database have many functions deal with it better and dont block main thread of UI.
... Maybe we need a parameter which called `onlineFilter: ` to call a API to backend and return the list.

**Comment by bosskmk** [comment]
@thegioiso 
Server-side sorting and filtering is possible using pagination.
https://pluto.weblaze.dev/rows-from-server-side

The problem is sorting and filtering large amounts of data on the client-side.

in the first way,
To use Isolate, code such as worker.js must be added in the web.

in the second way,
When processing sort, giving a delay of 1 microsecond for every N rows minimizes freezing of the UI.

I've tested both methods.
The first method is inconvenient for web because the user needs to add code such as worker.js.

The second method is simpler from the user's point of view, but it doesn't completely eliminate UI freezing, as it takes a little longer to sort and doesn't run in isolation.

**Comment by thegioiso** [comment]
... I mostly create UI on Flutter web so the first method maybe be a bad Breaking changes. But its will be fine if the package can create everything automatic when run `flutter pub get`.

**Comment by bosskmk** [comment]
@thegioiso 
There is an onSorted callback.

```dart
PlutoGrid(
  onSorted: (event) => print(event),
)
```

**Comment by thegioiso** [comment]
@MRKDaGods `onSorted` can callback when sort button is clicked, and you can call `gridStateManager?.setShowLoading(true);` for loading widget in grid. I dont have big data to test this callback, maybe you can call a timer function to set the loading off after your sorting processed.

**Comment by thegioiso** [comment]
@MRKDaGods   you can set a loading widget when sorting button is clicked with this callback. I dont have a big data to test so maybe you will need timer or other sync function to turn off loading after sorting is processed.

**Comment by MRKDaGods** [comment]
> @thegioiso There is an onSorted callback.
> 
> ```dart
> PlutoGrid(
>   onSorted: (event) => print(event),
>   // Execute the following, the internal sort is ignored 
>   // when the sort button is clicked, and sorting can be done manually through the onSorted callback.
>   // However, it is convenient to use the server-side pagination mentioned in the link above.
>   // Otherwise, you'll have to manually handle post-sorting.
>   onLoaded: (event) => event.stateManager.setSortOnlyEvent(true),
> )
> ```

This is exactly what I needed.
Now I can easily display a popup notifying the user that sorting is in progress for big datasets and meanwhile handle the sorting myself.

Thank you both!
