### ISSUE TITLE
[Bug] Ordering by date doesn't work well on paginated table

### ISSUE THREAD

**Issue by Macacoazul01** [bosskmk/pluto_grid#668]
### Steps to reproduce the bug

1. Create a paginated pluto grid with a `PlutoColumnType.date(format: 'dd/MM/yyyy')`
2. Try to order the table by the date column

### Expected results
Correct ordering

### Actual results
If you don't "cache" the full table by entering on each page, the order will be incorrect

### Code sample
[filtering.zip](https://github.com/bosskmk/pluto_grid/files/10136801/filtering.zip)

### Execution Environment
**Flutter version**
Channel stable, 3.3.9

**PlutoGrid version**
PlutoGrid - v5.4.6

**OS**
Web

**Comment by bosskmk** [comment]
I will fix the bug and release it.
Thanks for reporting the issue.

**Comment by Macacoazul01** [comment]
@bosskmk maybe if ordering is done using the originalValue getter (#670) instead of value, this can be solved.

I haven't seen the ordering code but this can be a solution.

**Comment by bosskmk** [comment]
DateFormat (intl) conversion process is performed for sorting date types.
This converts the format once and saves it if the value is not changed.
If you access (getter) the value of the cell, the value for sorting is saved once at the beginning, but this problem occurs because the values of other pages that are not opened in pagination are not accessed.
This will be fixed soon.

**Comment by bosskmk** [comment]
Fixed in PlutoGrid version 5.4.7.
This problem only seems to occur when the Date format is dd/MM/yyyy.
It doesn't happen with yyyy/MM/dd.

**Comment by Macacoazul01** [comment]
this is the default format here on Brasil, so for everyone using the package to display data it'll be a nice update. Tks!
