### ISSUE TITLE
[Help] Updating single row by id or ther means

### ISSUE THREAD

**Issue by dimityrivanov** [bosskmk/pluto_grid#677]
Hello is it possible to update single row when data has been changed in a popup or something else ?

**Comment by thegioiso** [comment]
@dimityrivanov  Usually, we will call a reload grid like below to update all the grid.
```
      gridAStateManager?.setShowLoading(true);
//add some delay here
      gridAStateManager?.removeAllRows();
      gridAStateManager?.resetCurrentState();

      gridARows = widget.buildRowA(gridARows);

      gridAStateManager?.appendRows(gridARows);

      gridAStateManager?.setShowLoading(false);
```
But if you would like to update only one 1 row without reload all the data. I think you should render your cell with  `renderer`:
```
PlutoColumn(
renderer: renderer,
)
```
Then build your cell with a stateful widget and add a listener for it. I commend a ValueNotifier.

```
widget.data.addListener(() {
if (mounted) {
            reloadCellWidget();
          }
});
```

**Comment by AminBhst** [comment]
Not many people explicitly mentioned this so I'm gonna say it here for anyone who is potentially facing issues with updating rows.
Before I talk about that, however, I think it goes without saying that removing all rows and then reinserting them or re-rendering the entire grid is extremely inefficient and must be avoided. Only the columns which require an update must be updated.
In order to update your rows, you need to fetch the reference to that row and update that.
First, override the `onLoaded` method in your PlutoGrid widget and acquire the `PlutoGridStateManager`  from it : 
```dart 
   onLoaded: (event) {
            _stateManager = event.stateManager;
          },
```
Then whenever you need to update a specific row, you'll need to fetch that row from the stateManager, set the new value for the cell which requires an update, then call `notifyListeners();` from the `PlutoGridStateManager`
```dart
final results = _stateManager?.rows.where((row) => row.cells["id"]?.value == id);
final cells = results.first.cells;
cells["status"]?.value ="new value";
_stateManager.notifyListeners();
```
hope it helps.
