### ISSUE TITLE
[Bug] Filter not working on number columns as expected

### ISSUE THREAD

**Issue by stingrayx** [bosskmk/pluto_grid#734]
### Steps to reproduce the bug

1. Go to the official column filter example page: https://weblaze.dev/pluto_grid/build/web/#feature/column-filtering
2. Enter 250 in the column "Number"

### Expected results
I would expect all rows displayed with a value > 250 in the column Number

### Actual results
It looks like the values are sorted as strings, not number 

This is reproducable also when using the example code provided here: https://pub.dev/packages/pluto_grid/example

**Comment by bosskmk** [comment]
@stingrayx 
Fixed in PlutoGrid 6.0.2 version.
Thanks for reporting the bug.

**Comment by mrtkp9993** [comment]
Is there any way to use version 6.0.2 with ```intl 0.17.0```? 

`Because every version of firebase_ui_auth depends on flutter_localizations from sdk which depends on intl 0.17.0, every version of firebase_ui_auth requires intl 0.17.0.
And because pluto_grid >=6.0.0 depends on intl ^0.18.0, firebase_ui_auth is incompatible with pluto_grid >=6.0.0.
So, because ... depends on both firebase_ui_auth any and pluto_grid ^6.0.0, version solving failed.`

**Comment by bosskmk** [comment]
@mrtkp9993 

https://dart.dev/tools/pub/dependencies#dependency-overrides

dependency_overrides:
  intl: '0.17.0'
