### ISSUE TITLE
[Bug] pluto_scrollbar.dart(482,39): error G036AE10F: Required named parameter 'devicePixelRatio'

### ISSUE THREAD

**Issue by selvam920** [bosskmk/pluto_grid#766]
/C:/Users/sksso/AppData/Local/Pub/Cache/git/pluto_grid-cc355af1351697f6aa790fb2ab6d9492a62efcc6/lib/s
rc/widgets/pluto_scrollbar.dart(482,39): error G036AE10F: Required named parameter 'devicePixelRatio'
must be provided. [D:\_sksmarket\sksmarket\build\windows\flutter\flutter_assemble.vcxproj]

Flutter (Channel beta, 3.8.0-10.1.pre, on Microsoft Windows [Version 10.0.22621.1265], locale en-US)

**Comment by bosskmk** [comment]
Support behavior in Flutter stable version.
In the case of the operation of the beta version or master version, updating to the stable version will solve the problem.
Currently, I do not make a preview version that can operate in the beta and master versions because I am managing this alone, but if there are people who help with this in the future, then I think I can consider the preview version.
