### ISSUE TITLE
[Other] Slow row selection effect

### ISSUE THREAD

**Issue by doonfrs** [bosskmk/pluto_grid#849]
Hi everyone.
I found that row selection is slow, taking 0.5 seconds to 1 or sometimes 2 seconds, and my pc is high-end. Also, I tried the online demo, they are fast, but when I build and run using the latest version pluto_grid: ^7.0.2, the grid act slow to the tap.
I've recorded a youtube video with a mouse click sound to make it easier to understand.
https://www.youtube.com/watch?v=Bu3B2wJP1RI&feature=youtu.be

Thank you!

**Comment by daniel-v** [comment]
I too experience it. It gives a really sluggish experience

**Comment by daniel-v** [comment]
So far what I found is that this is NOT a rendering issue. I tracked the widget rebuilds from `PlutoBaseCell._handleTapUp()` to the build methods of the rows (in Linux desktop build to give it as much resource as I could). That is just a few millis, shouldn't be noticable.

Then I wrapped the topmost `PlutoGrid` in a Listener somehow like this:

```dart
 Listener(
  onPointerDown: (PointerDownEvent event) {
    debugPrint('TAP: ${DateTime.now().millisecondsSinceEpoch}');
  },
  behavior: HitTestBehavior.translucent,
  child: PlutoGrind(),
)
```

and I observed the following:

between Listener`s `onPointerDown` callback and `_handleTapUp` the amount of time was around 350-360ms.

I wonder, what could cause this large latency,  @bosskmk ?

**Comment by doonfrs** [comment]
@daniel-v 
I tried with small and big grids, so it is not about rendering or performance. You are correct.
Something is delaying the tap-up or the function.

**Comment by marianodrz** [comment]
I had the same problem and detected it is when you have defined the onRowDoubleTap: (event) {} at the grid initialization. If you erase that, everything works well. 

In my case working without row double tap was not a serious problem, but they have to check whats causing it for better performance.

**Comment by AminBhst** [comment]
If anyone is facing this issue, just know that this isn't a pluto_grid problem. It's mainly a Flutter problem which is caused by a builtin 300ms delay which works fine on mobile. But since I guess the Flutter team doesn't really care all that much about desktop, they still haven't fixed this issue since 2022 when it became a known issue.

Anyway, if you want to fix this issue, clone pluto_grid and copy its directory to your projects main directory. [My commit](https://github.com/bosskmk/pluto_grid/commit/74e97f51e298bd93e9b24a3155d54644571b4bad) on my fork fixes this. It's not a clean solution but that's all we've got until this issue is handled explicitly by pluto_grid for the future versions
