### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by u382514** [bosskmk/pluto_grid#968]
I see a lot of pull requests and no movement since May.

**Comment by doonfrs** [comment]
I share the same concern.

**Comment by maurovitale** [comment]
I have the same concern too.

**Comment by doonfrs** [comment]
@u382514 ++ 
I hope he gets well soon 🙏, 
What do you recommend? should we fork the package or clone it to a new repository? because we need to be able to publish it to pub.dev and keep it maintained, I see some useful pull requests waiting to be reviewed, should we open a discord or telegram channel? please write some ideas so we can move on.

**Comment by doonfrs** [comment]
I forked it, I published it under the name pluto_grid_plus
https://github.com/doonfrs/pluto_grid_plus
https://pub.dev/packages/pluto_grid_plus

I upgraded the dependencies, I will check the current pull requests and try to merge them in the new fork, please try to create the pull requests there.

**Comment by DBOutlink** [comment]
> I forked it, I published it under the name pluto_grid_plus https://github.com/doonfrs/pluto_grid_plus https://pub.dev/packages/pluto_grid_plus
> 
> I upgraded the dependencies, I will check the current pull requests and try to merge them in the new fork, please try to create the pull requests there.

How can i use pluto_grid_export library with pluto_grid_plus?

**Comment by doonfrs** [comment]
> > I forked it, I published it under the name pluto_grid_plus https://github.com/doonfrs/pluto_grid_plus https://pub.dev/packages/pluto_grid_plus
> > I upgraded the dependencies, I will check the current pull requests and try to merge them in the new fork, please try to create the pull requests there.
> 
> How can i use pluto_grid_export library with pluto_grid_plus?

You can find the same class in the new fork, if you find a problem please open an issue, and I will manage to fix it.

**Comment by DBOutlink** [comment]
> > > I forked it, I published it under the name pluto_grid_plus https://github.com/doonfrs/pluto_grid_plus https://pub.dev/packages/pluto_grid_plus
> > > I upgraded the dependencies, I will check the current pull requests and try to merge them in the new fork, please try to create the pull requests there.
> > 
> > 
> > How can i use pluto_grid_export library with pluto_grid_plus?
> 
> You can find the same class in the new fork, if you find a problem please open an issue, and I will manage to fix it.

Thank you, I found It. Bur I'm not able to import It in my project like this: import 'package:pluto_grid_export...

**Comment by michaelbushe** [comment]
> https://pub.dev/packages/pluto_grid_plus

Please enable issues.  I'd like to fix this null exception in PlutoGridStateManager:
    for (var element in refColumns) {
      row.cells[element.field]!

Instead should throw an exception saying which field was not found in which row.

**Comment by doonfrs** [comment]
@michaelbushe done

**Comment by mattie-cmsp** [comment]
> @michaelbushe done

Don't mean to be pushy @michaelbushe, but I haven't seen you reply to any issues on your branch.  Is that where you're expecting us to open issues? (to note, the readme.md on the main page on pluto-grid-plus had a link to report an issue, but points back to the origin repository, not yours.)

**Comment by ecoant** [comment]
@bastaware @doonfrs there are some stale issues within the _new_ package as well now, is there any way we could alert the relevant author/owner of this fantastic, _original_ package to pass maintenance permissions on to someone else? I volunteer to be one of the maintainers, as the recent 3.19.0 flutter sdk includes a breaking change re: `RawKeyEvent` in both this and the forked `pluto_grid_plus` package. I do not feel that a new package was needed as a better solution would be to pass maintenance on. For example, in the forked version, the `export` package was not published to pub.dev and there is no way I can see to retain this functionality. We are currently two hops deep in an unmaintained package hole. @bosskmk did great work and it would be sad to see the project wither.

**Comment by bastaware** [comment]
I've tried contacting @bosskmk  directly via email, but he no longer replies. I'm afraid a fork is the only solution. Also, it's unfortunate that the new pluto_grid_plus also seems stalled.

**Comment by doonfrs** [comment]
@bastaware Hi,
The new package is not stalled, all are welcome to create pull requests, regarding some issues created, I will try to review them this week, but it depends on my workload.
Remember it is an open source project, it should be based on collaboration.

**Comment by doonfrs** [comment]
@ecoant 
* I understand your concerns, I started the fork for myself because I heavily depend on it for my project and I found it would be better to share the updates.
* You can check the commit log there is a lot of work done to keep it up to date with the latest Flutter version and fix some major bugs, also added some new features, so I can keep this version working as the current maintainer is not replying and someone in contact with him mentioned that he lost the motivation to continue so we defiantly need a new version.
* Replying to issues takes a lot of time as I am not the main developer, I need to repeat the errors locally or investigate the code ( not my code as you know) which is not possible for me all the time, I have busy schedule, but I will do my best.
* Regarding the write access, anyone is welcome, and I already reviewed and merged pull requests on time.
* I can add reviewers to the new package and I am open to any suggestions, this is the best grid package for Flutter and it should continue, but it is also a big project and requires more collaboration.

**Comment by aymswick** [comment]
https://github.com/doonfrs/pluto_grid_plus/pull/9

**Comment by doonfrs** [comment]
@aymswick merged 🙏🙏

**Comment by doonfrs** [comment]
Hi @Macacoazul01
That will be great, I am waiting for the developers to join.

**Comment by michaelbushe** [comment]
I’d like to help.  GitHub @michaelbushe

MindfulSoftware.com

Mike Bushe
***@***.***
+1-508-625-1235

**Comment by doonfrs** [comment]
@michaelbushe invitation sent

**Comment by Macacoazul01** [comment]
@doonfrs can you please add me too?

**Comment by doonfrs** [comment]
@Macacoazul01 invitation sent

**Comment by VittorioParagallo** [comment]
Good day everybody,
i started using this package and when i discovered is obsolete i switched to pluto_grid_plus, i see people keeping to send pull requests on pluto_grid and a lot of forks. It feels that there is a lot of work gettin lost and wasted. Is pluto_grid_plus the continuation of grid_plus? in that case i feel we should find a way to tell people to move there maybe commenting on pull requests till the overall activity of pluto_grid_plus takes over pluto_grid and will go up in result searchs. I'm already from time to time commenting on commits and pull request to move here. What else can we do?
