### ISSUE TITLE
[Problem] Conflict with "intl 1.9.0"

### ISSUE THREAD

**Issue by softplaceio** [bosskmk/pluto_grid#996]
Hello, 

I can't update "intel: ^1.9.0" because plot_grid needs "intl: ^1.8.0".
How can I resolve my situation?

```
Resolving dependencies...
Because pluto_grid 7.0.2 depends on intl ^0.18.0 and no versions of pluto_grid match >7.0.2 <8.0.0, pluto_grid ^7.0.2 requires intl ^0.18.0.
So, because budget_generator depends on both intl ^0.19.0 and pluto_grid ^7.0.2, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on intl: flutter pub add intl:^0.18.1
exit code 1
```

**Comment by NNanosoft** [comment]
Hello dears, 
I am facing the same issue. The dependencies need to be updated.
I have seen that there is no commits since 8 months on git repository, does it mean that the project was abandoned from developers?

**Comment by doonfrs** [comment]
@NNanosoft 
https://pub.dev/packages/pluto_grid_plus

**Comment by NNanosoft** [comment]
thank you @doonfrs  
but is there any official communication from the project team saying that the original project is not maintained anymore?
@bosskmk could you please give us any feedback?

**Comment by reyadd-az** [comment]
I faced a similar issue, 
pluto_grid: ^7.0.2 required intl: ^0.18.0, but had few other packages that require  intl: ^0.17.0. and the project was not building because the dependencies could not be resolved.

I solved it as follows: I copied the folder (pluto_grid-7.0.2) from the cache Pub\Cache\hosted\pub.dev\pluto_grid-7.0.2 to a local folder, then changed the pubspec entry to intl: ^0.17.0. saved and ran pub get, then moved pluto_grid-7.0.2 back to cache.
now my project builds with no conflicts.
I know the approach my not be the best but it was my last resort. at lease I resolved the conflict.
